name: Deploy GyaCity Construction

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Deploy to VPS
          uses: appleboy/ssh-action@v1.2.0

          with:
            host: ${{ vars.SERVER_HOST }}
            username: root
            key: ${{ secrets.SERVER_SSH_KEY }}
            port: 22
            script_stop: true

            script: |
              export NVM_DIR="/root/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

              nvm use 20

              node -v 
              npm -v
              
              cd /var/www/production/gyacity

              git fetch origin
              git reset --hard origin/main

              npm install

              npm run build

              echo "Deployment completed"
